# Generated by Django 5.1.2 on 2024-10-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('prefixo', models.CharField(blank=True, max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
                ('data_nasc', models.DateField()),
                ('estado_civil', models.CharField(choices=[('CASADO', 'Casado'), ('SOLTEIRO', 'Solteiro'), ('DIVORCIADO', 'Divorciado')], default='SOLTEIRO', max_length=10)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('possui_habilitacao', models.BooleanField(default=False)),
                ('tipo_habilitacao', models.CharField(blank=True, choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D')], max_length=1, null=True)),
                ('carteira_profissional', models.BooleanField(default=False)),
                ('serie_carteira_profissional', models.CharField(blank=True, max_length=10, null=True)),
                ('formacao', models.CharField(choices=[('1G_COMPLETO', '1 Grau Completo'), ('2G_COMPLETO', '2 Grau Completo'), ('2G_INCOMPLETO', '2 Grau Incompleto'), ('SUPERIOR', 'Superior Completo'), ('SUPERIOR_INCOMPLETO', 'Superior Incompleto'), ('POS_GRADUACAO', 'Pós-Graduação'), ('MBA', 'MBA'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], default='1G_COMPLETO', max_length=50)),
                ('curso', models.CharField(blank=True, max_length=500, null=True)),
                ('ano_conclusao', models.IntegerField(blank=True, null=True)),
                ('empresa_atual', models.CharField(blank=True, max_length=200, null=True)),
                ('segmento_atual', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_atual', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio_atual', models.DateField(blank=True, null=True)),
                ('data_saida_atual', models.DateField(blank=True, null=True)),
                ('atribuicoes_atual', models.TextField(blank=True, max_length=200, null=True)),
                ('empresa_anterior_1', models.CharField(blank=True, max_length=200, null=True)),
                ('segmento_anterior_1', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_anterior_1', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio_anterior_1', models.DateField(blank=True, null=True)),
                ('data_saida_anterior_1', models.DateField(blank=True, null=True)),
                ('atribuicoes_anterior_1', models.TextField(blank=True, max_length=200, null=True)),
                ('empresa_anterior_2', models.CharField(blank=True, max_length=200, null=True)),
                ('segmento_anterior_2', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo_anterior_2', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio_anterior_2', models.DateField(blank=True, null=True)),
                ('data_saida_anterior_2', models.DateField(blank=True, null=True)),
                ('atribuicoes_anterior_2', models.TextField(blank=True, max_length=200, null=True)),
                ('cargo_pretendido', models.CharField(max_length=100)),
                ('faixa_salarial_desejada', models.CharField(max_length=100)),
            ],
        ),
    ]
